### ISSUE TITLE
"did not find control file in debian archive"

### ISSUE THREAD

**Issue by benjojo** [tcolgate/godinstall#41]
Pretty sure that there is a control in this one, I made the package using FPM, looking at the code that this error leads up to, I'm not really that sure how this could happen.

[sample.zip.zip](https://github.com/tcolgate/godinstall/files/335856/sample.zip.zip)

**Comment by tcolgate** [comment]
Hey,
  I've had a very quick look. The ar and control.gz look OK if I check them
manually, and the control file parses if I plug it in as a unit test. Not
sure what is going on here. I'll try and take a look later today.
  Thanks for the report.

**Comment by tcolgate** [comment]
Did you happen to create that deb using fpm on a Mac? The ar entries all had a trailing / , googling around suggests that's a BSD'ism. I've pushed a fix, so the package should upload. I'll need to read around to understand the purpose of that / at some point though.

**Comment by benjojo** [comment]
I actually made that with FPM on Ubuntu 14.4, No idea why it would make it like that

**Comment by tcolgate** [comment]
That is odd. I've seen other issues with FPM before, but it's usually
rubbish control file content. I guess this might be a GNU ar update?
Strictly speaking, it's a bug in the upstream go ar package I'm using. But
I can work round it for now. Thanks for the bug report.

**Comment by benjojo** [comment]
Confirmed the fix on master fixes this. Thanks!
